### PR TITLE
Updated readme

### PR DESCRIPTION
**Pull request by TempUser13**
Added a few things and fixed the english.

### CODE REVIEW

**Review by casualsnek — CHANGES_REQUESTED** [review]
Can you add back instructions for setting up ffmpeg in windows ?
The site just gives the zip not an installer so people might get confused on how to set it up !

**Comment by TempUser13** [comment]
I added instructions to install ffmpeg on windows, I wrote the original change before you added the instructions yourself.

**Comment by TempUser13** [comment]
Apologies if I've done anything incorrectly, I haven't used the changes requested ui before.

**Comment by casualsnek** [comment]
> Apologies if I've done anything incorrectly, I haven't used the changes requested ui before.

No problem ! There seems to be large section of content repeating, i will correct it myself and add some section. 
I will make a comment when i have made the changes.

Update: I have added a commit updating at, can you check if it correct before i merge this ?

**Pull request merged**
